# Generated by Django 6.0.2 on 2026-03-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('agente_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código SIC')),
                ('nombre_agente', models.CharField(max_length=255)),
                ('actividad', models.CharField(max_length=100)),
                ('clasificacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricasIntercambiosHidrologia',
            fields=[
                ('id_contexto', models.AutoField(primary_key=True, serialize=False)),
                ('enlace_id', models.CharField(max_length=50)),
                ('fecha_operacion', models.DateField()),
                ('energia_exportada_tie', models.DecimalField(decimal_places=4, max_digits=18)),
                ('energia_importada_tie', models.DecimalField(decimal_places=4, max_digits=18)),
                ('nivel_embalses_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_enficc_probabilistico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energia_remanente_diaria', models.DecimalField(decimal_places=4, max_digits=18)),
                ('demanda_desconectable_verificada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fuente_archivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetricasContratosPrivados',
            fields=[
                ('contrato_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contraparte_id', models.CharField(max_length=50)),
                ('fecha_operacion', models.DateField()),
                ('periodo_hora', models.PositiveIntegerField()),
                ('cantidad_despachada_kwh', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tarifa_contrato_cop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_despacho_pc_pd', models.CharField(max_length=10)),
                ('mercado_r_nr', models.CharField(max_length=10)),
                ('fuente_archivo', models.CharField(max_length=255)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.agente')),
            ],
        ),
        migrations.CreateModel(
            name='MetricasDemandaBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField()),
                ('demanda_no_regulada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('demanda_regulada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('perdidas_no_regulada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('perdidas_regulada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('demanda_no_cubierta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('factor_ajuste_o_e_f', models.DecimalField(decimal_places=6, max_digits=10)),
                ('fuente_archivo', models.CharField(max_length=255)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.agente')),
            ],
        ),
        migrations.CreateModel(
            name='MetricasMercadoPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField()),
                ('periodo_hora', models.PositiveIntegerField()),
                ('precio_bolsa_nacional', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_escasez_activacion', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_marginal_escasez', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_escasez_ponderado', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_equivalente_real_energia', models.DecimalField(decimal_places=4, max_digits=18)),
                ('trm_dia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente_archivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Métricas Mercado Precios',
                'unique_together': {('fecha_operacion', 'periodo_hora')},
            },
        ),
        migrations.CreateModel(
            name='MetricasTransaccionesLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField()),
                ('compras_bolsa_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ventas_bolsa_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('compras_reconciliacion_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ventas_reconciliacion_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('responsabilidad_agc_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('servicios_sic_cnd_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('neto_cargo_confiabilidad_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_srpf_cop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fuente_archivo', models.CharField(max_length=255)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.agente')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('recurso_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=255)),
                ('capacidad_efectiva_neta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tipo_tecnologia', models.CharField(max_length=100)),
                ('fecha_operacion', models.DateField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('combustible', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_recurso', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='data.agente')),
            ],
        ),
        migrations.CreateModel(
            name='MetricasGeneracionCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField()),
                ('periodo_hora', models.PositiveIntegerField()),
                ('generacion_real', models.DecimalField(decimal_places=4, max_digits=18)),
                ('generacion_ideal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('generacion_seguridad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('disponibilidad_comercial', models.DecimalField(decimal_places=4, max_digits=18)),
                ('disponibilidad_real', models.DecimalField(decimal_places=4, max_digits=18)),
                ('causa_restriccion', models.TextField(blank=True, null=True)),
                ('fuente_archivo', models.CharField(max_length=255)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='MetricasConfiabilidadSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField()),
                ('oef_diaria', models.DecimalField(decimal_places=4, max_digits=18)),
                ('precio_cargo_confiabilidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('remuneracion_real_individual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('desviacion_oef_ajustada', models.DecimalField(decimal_places=4, max_digits=18)),
                ('flag_activacion_escasez', models.BooleanField(default=False)),
                ('fuente_archivo', models.CharField(max_length=255)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.recurso')),
            ],
        ),
    ]
