# Generated by Django 6.0.2 on 2026-03-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255, verbose_name='Nombre del Usuario / Razón Social')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT (Número de Identificación Tributaria)')], default='NIT', max_length=3)),
                ('numero_identificacion', models.CharField(max_length=25, unique=True, verbose_name='Número de Identificación')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion_facturacion', models.TextField(verbose_name='Dirección de Facturación')),
                ('fecha_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frontera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50)),
                ('numero_factura', models.CharField(max_length=50)),
                ('frontera_sic', models.CharField(max_length=50)),
                ('numero_medidor', models.CharField(max_length=50)),
                ('comercializador', models.CharField(max_length=150)),
                ('operador_red', models.CharField(choices=[('CEO', 'Compañía Energética de Occidente S.A.S. ESP'), ('EMCARTAGO', 'Empresas Municipales de Cartago S.A.S. E.S.P.'), ('RUITOQUE', 'Ruitoque S.A. E.S.P.'), ('CEDEC', 'Centrales Eléctricas del Cauca S.A. E.S.P.'), ('EMCALI', 'Empresas Municipales de Cali E.I.C.E. E.S.P.'), ('ENEL', 'Enel Colombia SA ESP'), ('AFINIA', 'Caribemar de la Costa S.A.S. E.S.P. (Afinia)'), ('ELECTROCAQUETA', 'Electrificadora del Caquetá S.A. E.S.P.'), ('ELECTROHUILA', 'Electrificadora del Huila S.A. E.S.P.'), ('ELECTROMETA', 'Electrificadora del Meta S.A. E.S.P.'), ('EBSA', 'Empresa de Energía de Boyacá S.A. E.S.P.'), ('ENERCA', 'Empresa de Energía de Casanare S.A. E.S.P.'), ('EEP', 'Empresa de Energía de Pereira S.A. E.S.P.'), ('EBP', 'Empresa de Energía del Bajo Putumayo S.A. E.S.P.'), ('CELSIA', 'Celsia Colombia S.A. E.S.P.'), ('EDQ', 'Empresa de Energía del Quindío S.A. E.S.P.'), ('EMS', 'Empresa de Energía de Arauca E.S.P.'), ('CHEC', 'Central Hidroeléctrica de Caldas S.A. E.S.P.'), ('CEDENAR', 'Centrales Eléctricas de Nariño S.A. E.S.P.'), ('CENS', 'Centrales Eléctricas del Norte de Santander S.A. E.S.P.'), ('ESSA', 'Electrificadora de Santander S.A. E.S.P.'), ('AIR-E', 'Air-e S.A.S. E.S.P.'), ('EPM', 'Empresas Públicas de Medellín E.S.P.')], max_length=100)),
                ('departamento', models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANTIOQUIA', 'Antioquia'), ('ARAUCA', 'Arauca'), ('ATLANTICO', 'Atlántico'), ('BOGOTA', 'Bogotá D.C.'), ('BOLIVAR', 'Bolívar'), ('BOYACA', 'Boyacá'), ('CALDAS', 'Caldas'), ('CAQUETA', 'Caquetá'), ('CASANARE', 'Casanare'), ('CAUCA', 'Cauca'), ('CESAR', 'Cesar'), ('CHOCO', 'Chocó'), ('CORDOBA', 'Córdoba'), ('CUNDINAMARCA', 'Cundinamarca'), ('GUAINIA', 'Guainía'), ('GUAVIARE', 'Guaviare'), ('HUILA', 'Huila'), ('GUAJIRA', 'La Guajira'), ('MAGDALENA', 'Magdalena'), ('META', 'Meta'), ('NARINO', 'Nariño'), ('NORTE_SANTANDER', 'Norte de Santander'), ('PUTUMAYO', 'Putumayo'), ('QUINDIO', 'Quindío'), ('RISARALDA', 'Risaralda'), ('SAN_ANDRES', 'San Andrés'), ('SANTANDER', 'Santander'), ('SUCRE', 'Sucre'), ('TOLIMA', 'Tolima'), ('VALLE_CAUCA', 'Valle del Cauca'), ('VAUPES', 'Vaupés'), ('VICHADA', 'Vichada')], max_length=50)),
                ('municipio_frontera', models.CharField(max_length=100, verbose_name='Municipio')),
                ('mercado', models.CharField(choices=[('R', 'Regulado'), ('NR', 'No Regulado')], max_length=2)),
                ('nivel_tension', models.CharField(choices=[('NT1', 'NT1'), ('NT2', 'NT2'), ('NT3', 'NT3'), ('NT4', 'NT4')], max_length=3)),
                ('direccion_frontera', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fronteras', to='clientes.cliente')),
            ],
        ),
    ]
