# Generated by Django 6.0.2 on 2026-04-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_frontera_operador_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontera',
            name='nivel_tension',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
