# Generated by Django 6.0.2 on 2026-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_frontera_nivel_tension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontera',
            name='operador_red',
            field=models.CharField(choices=[('EPMD - EPM Mercado de Comercialización - ANTIOQUIA', 'EPM - ANTIOQUIA'), ('ENID - ENELAR Mercado de Comercialización - ARAUCA', 'ENELAR - ARAUCA'), ('EBPD - BAJO PUTUMAYO  Mercado de Comercialización - BAJO PUTUMAYO', 'EBP - BAJO PUTUMAYO'), ('ENDD - ENEL Mercado de Comercialización - BOGOTA - CUNDINAMARCA', 'ENEL - BOGOTÁ'), ('EBSD - EBSA Mercado de Comercialización - BOYACA', 'EBSA - BOYACÁ'), ('CHCD - CHEC S.A. E.S.P. BIC Mercado de Comercialización - CALDAS', 'CHEC - CALDAS'), ('EMID - EMCALI Mercado de Comercialización - CALI - YUMBO - PUERTO TEJADA', 'EMCALI - CALI'), ('CQTD - ELECTROCAQUETA Mercado de Comercialización - CAQUETA', 'ELECTROCAQUETA - CAQUETÁ'), ('CMMD - CARIBEMAR Mercado de Comercialización - CARIBE MAR', 'AFINIA - CARIBE MAR'), ('CSID - AIR-E Mercado de Comercialización - CARIBE SOL', 'AIRE - CARIBE SOL'), ('EEPD - EEP Mercado de Comercialización - CARTAGO', 'EMCARTAGO - CARTAGO'), ('CASD - ENERCA Mercado de Comercialización - CASANARE', 'ENERCA - CASANARE'), ('CEOD - CEO S.A.S E.S.P. Mercado de Comercialización - CAUCA', 'CEO - CAUCA'), ('EDPD - DISPAC S.A. E.S.P. Mercado de Comercialización - CHOCO', 'DISPAC - CHOCÓ'), ('EGVD - ENERGUAVIARE Mercado de Comercialización - GUAVIARE', 'ENERGUAVIARE - GUAVIARE'), ('HLAD - ELECTROHUILA Mercado de Comercialización - HUILA', 'ELECTROHUILA - HUILA'), ('EMSD - EMSA Mercado de Comercialización - META', 'EMSA - META'), ('CDND - CEDENAR Mercado de Comercialización - NARIÑO', 'CEDENAR - NARIÑO'), ('CNSD - CENS Mercado de Comercialización - NORTE DE SANTANDER', 'CENS - NORTE DE SANTANDER'), ('EEPD - EEP Mercado de Comercialización - PEREIRA', 'EEP - PEREIRA'), ('EMED - EMEE Mercado de Comercialización - POPAYAN - PURACE', 'EMEE - POPAYÁN'), ('EPTD - PUTUMAYO Mercado de Comercialización - PUTUMAYO', 'EPT - PUTUMAYO'), ('EDQD - EDEQ Mercado de Comercialización - QUINDIO', 'EDEQ - QUINDÍO'), ('RTQD - RUITOQUE Mercado de Comercialización - RUITOQUE', 'RUITOQUE - RUITOQUE'), ('ESSD - ESSA Mercado de Comercialización - SANTANDER', 'ESSA - SANTANDER'), ('EPSD - CELSIA COLOMBIA Mercado de Comercialización - TOLIMA', 'CELSIA - TOLIMA'), ('CETD - CETSA Mercado de Comercialización - TULUA', 'CETSA - TULUÁ'), ('EPSD - CELSIA COLOMBIA Mercado de Comercialización - VALLE DEL CAUCA', 'CELSIA - VALLE DEL CAUCA')], max_length=255),
        ),
    ]
