# Generated by Django 6.0.2 on 2026-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_frontera_operador_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='terminos_aceptados',
            field=models.BooleanField(default=False, verbose_name='Aceptó términos'),
        ),
    ]
