# Generated by Django 6.0.2 on 2026-04-08 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_fecha_aceptacion_cliente_terminos_aceptados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_aceptacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='terminos_aceptados',
        ),
        migrations.CreateModel(
            name='AceptacionTerminos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255, verbose_name='Usuario que aceptó')),
                ('correo_asociado', models.EmailField(max_length=254, verbose_name='Correo en el momento de aceptación')),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_terminos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
