# Generated by Django 6.0.2 on 2026-03-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mes', models.DateField(unique=True, verbose_name='Mes/Año (Día 1)')),
                ('valor_ipc', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='IPC del Mes')),
                ('valor_ipp', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='IPP del Mes')),
            ],
            options={
                'verbose_name': 'Periodo e Índices',
                'verbose_name_plural': 'Periodos e Índices',
                'ordering': ['-fecha_mes'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_pld', models.CharField(default='FIJO', max_length=20)),
                ('precio_g_base', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('precio_c_base', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ipp_base', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('ipc_base', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('frontera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.frontera')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_red', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_red', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentePR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_red', models.CharField(max_length=100)),
                ('nivel_tension', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tipo_indice', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_indice', models.DateField(blank=True, null=True)),
                ('valor_indice', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_indexado', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.contrato')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_red', models.CharField(max_length=100)),
                ('nivel_tension', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tipo_indice', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_indice', models.DateField(blank=True, null=True)),
                ('valor_indice', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_indexado', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.contrato')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.IntegerField()),
                ('consumo_activo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumo_reactivo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('es_estimado', models.BooleanField(default=False)),
                ('frontera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.frontera')),
            ],
            options={
                'indexes': [models.Index(fields=['frontera', 'fecha'], name='liquidacion_fronter_9c946b_idx')],
            },
        ),
    ]
